create table publishers (
	publisherID INT GENERATED BY DEFAULT AS IDENTITY,
	publisherName VARCHAR (30) NOT NULL,
	PRIMARY KEY (publisherID)
);

create table authors (
	authorID INT GENERATED BY DEFAULT AS IDENTITY,
	firstName VARCHAR (20) NOT NULL,
	lastName VARCHAR (30) NOT NULL,
	PRIMARY KEY (authorID)
);

create table titles (
	isbn VARCHAR (20) NOT NULL,
	title VARCHAR (100) NOT NULL,
	editionNumber INT NOT NULL,
	copyright VARCHAR (4) NOT NULL,
	publisherID INT NOT NULL,
	imageFile VARCHAR (20) NOT NULL,
	price real NOT NULL,
	PRIMARY KEY (isbn)
);

create table authorISBN (
	authorID INT NOT NULL,
	isbn VARCHAR (20) NOT NULL
);

create table customer (
        id INT GENERATED BY DEFAULT AS IDENTITY,
	userEmail VARCHAR (100) NOT NULL,
	userPwd VARCHAR (20) NOT NULL,
        orderid INT DEFAULT 0,
	PRIMARY KEY (userEmail)
);

create table orders (
        orderID INT NOT NULL,
        userID INT NOT NULL,
        isbn VARCHAR (20) NOT NULL,
        quantity INT NOT NULL
);
